services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3314:3306"      # exposes MySQL to your local machine and LAN
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_server
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"        # access phpMyAdmin at http://localhost:8080
    depends_on:
      - mysql
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge
